### ISSUE TITLE
update lengths of stay using new paper while calculating DALYs

### ISSUE THREAD

**Issue by yangclaraliu** [yangclaraliu/covid_vac_africa#4]
https://www.medrxiv.org/content/10.1101/2020.07.17.20155218v14.full.pdf

**Comment by mert0248** [comment]
Updated using values from Leclerc et al https://doi.org/10.1186/s12913-021-06509-x

For hospitalised cases with no icu stay use mean LoS of 9.60 days.
For hospitalised cases with any part of the stay in icu we use the weighted average of total time in hospital across all pathways involving a stay in critical care.
